name: money_expense_dot
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_smart_dialog: ^4.9.8+9
  flutter_spinkit: 5.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  icons_launcher: ^3.0.2
  intl: ^0.19.0
  logger: ^2.4.0
  path_provider: ^2.0.15
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_gen:
  output: lib/shared/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/fonts/

  fonts:
    - family: SourceSansPro
      fonts:
        # - asset: assets/fonts/SourceSansPro-Thin.ttf
        #   weight: 100
        - asset: assets/fonts/SourceSansPro-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/SourceSansPro-Light.otf
          weight: 300
        - asset: assets/fonts/SourceSansPro-Regular.otf
          weight: 400
        # - asset: assets/fonts/SourceSansPro-Medium.otf
        #   weight: 500
        - asset: assets/fonts/SourceSansPro-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Bold.otf
          weight: 700
        # - asset: assets/fonts/SourceSansPro-ExtraBold.otf
        #   weight: 800
        - asset: assets/fonts/SourceSansPro-Black.otf
          weight: 900
